version: 2.0

jobs:
    product:
        docker:
            - image: gaku3601/circleci-base-image:latest
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run: echo "product!!!"
            - run:
              name: Install Docker client
              command: |
                set -x
                VER="17.03.0-ce"
                curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                sudo mv /tmp/docker/* /usr/bin
            - run: chmod 777 ./.circleci/product.deploy.sh
            - run: bash ./.circleci/product.deploy.sh
workflows:
    version: 2
    test_and_deploy:
        jobs:
            - product:
                context: gitlab
                filters:
                    branches:
                      ignore: /.*/
                    tags:
                      only: /.*/
